# Generated by Django 3.0.6 on 2020-07-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_day', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=400)),
            ],
        ),
    ]
