# Generated by Django 3.0.6 on 2020-07-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frombeforeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='d_day',
            new_name='dday',
        ),
    ]
