# Generated by Django 3.1.dev20191108131413 on 2020-07-18 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frombeforeapp', '0002_auto_20200714_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edit_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
